version: "3"

services:
    frontend:
        build:
            context: ./Frontend
            dockerfile: Dockerfile
        ports:
            - "3002:3002"
        restart: always

    backend:
        build:
            context: ./Backend
            dockerfile: Dockerfile
        ports:
            - "9999:9999"
        restart: always